name: Python CI

on: push # 푸시 이벤트가 발생할 때만 실행

jobs:
  test:
    runs-on: ubuntu-latest

    steps: # 현재 타겟이 되는 브랜치로 이동
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        architecture: x64

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root

    - name: Run tests with pytest # 테스트 실행
      run: |
        poetry run python -m pytest tests -s
